import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/lib/db";
import Event from "@/models/Event";
import Department from "@/models/Department";
import User from "@/models/User";
import Notification from "@/models/Notification";
import {requireUser,invalid} from "@/lib/api";
export async function GET(request:NextRequest){const auth=await requireUser();if(auth.error)return auth.error;try{const p=request.nextUrl.searchParams;const q=p.get("q");const filter:any={};if(auth.user!.role==="OPERATOR")filter.operator=auth.user!.id;if(auth.user!.role==="DEPARTMENT_OFFICER")filter.assignedOfficer=auth.user!.id;if(p.get("status"))filter.status=p.get("status");if(p.get("priority"))filter.priority=p.get("priority");if(p.get("department"))filter.department=p.get("department");if(q)filter.$or=["eventId","callerName","category","location"].map(k=>({[k]:{$regex:q,$options:"i"}}));await connectDB();const page=Math.max(1,Number(p.get("page"))||1),limit=Math.min(100,Math.max(1,Number(p.get("limit"))||10));const [items,total]=await Promise.all([Event.find(filter).populate("department operator assignedOfficer","name email").sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),Event.countDocuments(filter)]);return NextResponse.json({items,total,page,limit});}catch{return NextResponse.json({error:"Database unavailable"},{status:503});}}
export async function POST(request:NextRequest){const auth=await requireUser(["ADMIN","OPERATOR"]);if(auth.error)return auth.error;try{const body=await request.json();for(const k of ["callerName","phoneNumber","location","category","description"])if(!body[k])return invalid(`${k} is required`);await connectDB();const department=typeof body.department==="string"?await Department.findOne({name:body.department}):null;const officer=department?await User.findOne({role:"DEPARTMENT_OFFICER",department:department._id,active:true}):null;if(!department)return invalid("Selected department was not found");if(!officer)return NextResponse.json({error:"No active Department Officer is assigned to the selected department"},{status:409});const event=await Event.create({...body,department:department._id,assignedOfficer:officer._id,status:"Assigned",operator:auth.user!.id,eventId:`EV-9141-${Date.now().toString().slice(-6)}`,history:[{action:"Registered",details:"Citizen event registered",actor:auth.user!.id}]});await Notification.create({user:officer._id,title:"New assigned event",message:`${event.eventId}: a new ${event.priority.toLowerCase()} priority case is ready for action.`,type:"assignment",event:event._id});return NextResponse.json(event,{status:201});}catch{return invalid("Unable to register event");}}
