"use client";

import {Fragment,useEffect,useLayoutEffect,useMemo,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {Activity,Bell,Building2,CheckCircle2,ClipboardList,FileBarChart,LayoutDashboard,LogOut,MapPin,MessageSquare,MonitorCog,Plus,Search,Settings,Sun,Moon,Users,X} from "lucide-react";
import {Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import type {Role} from "@/lib/auth";

type EventRow={_id?:string;id:string;caller:string;category:string;department:string;location:string;priority:string;status:string;time:string;operator?:string;assignedOfficer?:string};
type Notice={_id:string;title:string;message:string;type:string;read:boolean;createdAt:string;event?:string};
const seed:EventRow[]=[{id:"EV-9141-001",caller:"Abel Tesfaye",category:"Road accident",department:"Traffic Police",location:"Kebele 04, Adama",priority:"Critical",status:"Ongoing",time:"09:42"},{id:"EV-9141-002",caller:"Marta Bekele",category:"Water leakage",department:"Water",location:"Bole Road",priority:"High",status:"Assigned",time:"09:18"},{id:"EV-9141-003",caller:"Selamawit A.",category:"Medical emergency",department:"Health",location:"Adama Hospital",priority:"Critical",status:"New",time:"08:31"},{id:"EV-9141-004",caller:"Tadesse B.",category:"Waste collection",department:"Sanitation",location:"Kebele 06",priority:"Low",status:"Solved",time:"08:06"}];
const nav:Record<Role,[string,string][]>={ADMIN:[["dashboard","Dashboard"],["analytics","Analytics"],["users","Users"],["departments","Departments"],["all-events","All Events"],["reports","Reports"],["settings","Settings"],["profile","Profile"],["notifications","Notifications"]],OPERATOR:[["dashboard","Dashboard"],["register-event","Register Event"],["manage-events","Manage Events"],["advanced-search","Advanced Search"],["follow-up","Follow Up"],["event-history","Event History"],["notifications","Notifications"],["profile","Profile"]],SUPERVISOR:[["dashboard","Dashboard"],["operator-performance","Operator Performance"],["department-performance","Department Performance"],["response-time","Response Time"],["critical-events","Critical Events"],["reports","Reports"],["analytics","Analytics"],["notifications","Notifications"]],DEPARTMENT_OFFICER:[["dashboard","Dashboard"],["assigned-events","Assigned Events"],["update-progress","Update Progress"],["completion-notes","Completion Notes"],["remarks-history","Remarks History"],["event-timeline","Event Timeline"],["notifications","Notifications"],["profile","Profile"]]};
const titles:Record<Role,string>={ADMIN:"Administrator",OPERATOR:"Operator",SUPERVISOR:"Supervisor",DEPARTMENT_OFFICER:"Department Officer"};
const copy={en:{Dashboard:"Dashboard",Notifications:"Notifications",Profile:"Profile",Settings:"Settings",Reports:"Reports",Overview:"Overview",Logout:"Sign out",Language:"Language",Theme:"Theme",Light:"Light",Dark:"Dark",events:"events",tasks:"tasks",updates:"updates",Performance:"Performance"},am:{Dashboard:"ዳሽቦርድ",Notifications:"ማሳወቂያዎች",Profile:"መገለጫ",Settings:"ቅንብሮች",Reports:"ሪፖርቶች",Overview:"አጠቃላይ እይታ",Logout:"ውጣ",Language:"ቋንቋ",Theme:"ገጽታ",Light:"ብርሃን",Dark:"ጨለማ",events:"ክስተቶች",tasks:"ተግባራት",updates:"ዝማኔዎች",Performance:"አፈጻጸም"},om:{Dashboard:"Daashboordii",Notifications:"Beeksisa",Profile:"Piroofaayilii",Settings:"Qindaa'ina",Reports:"Gabaasa",Overview:"Cuunfaa",Logout:"Ba'i",Language:"Afaan",Theme:"Bifa",Light:"Ifa",Dark:"Dukkana",events:"taateewwan",tasks:"hojiiwwan",updates:"haaromsa",Performance:"Raawwii"}};
const phrases={en:{"Events by month":"Events by month","Cases handled by month":"Cases handled by month","Response-time trend":"Response-time trend","Case status":"Case status","Service activity heat map":"Service activity heat map","Cases by location and time":"Cases by location and time","Based on recorded event locations and intake times.":"Based on recorded event locations and intake times."},am:{"Events by month":"በወር የተመዘገቡ ክስተቶች","Cases handled by month":"በወር የተያዙ ጉዳዮች","Response-time trend":"የምላሽ ጊዜ አዝማሚያ","Case status":"የጉዳይ ሁኔታ","Service activity heat map":"የአገልግሎት እንቅስቃሴ ሙቀት ካርታ","Cases by location and time":"ጉዳዮች በቦታ እና በጊዜ","Based on recorded event locations and intake times.":"በተመዘገቡ ቦታዎች እና የመቀበያ ጊዜዎች ላይ የተመሠረተ።"},om:{"Events by month":"Taateewwan ji'aan","Cases handled by month":"Dhimmoota ji'aan raawwataman","Response-time trend":"Adeemsa yeroo deebii","Case status":"Haala dhimmaa","Service activity heat map":"Kaartaa ho'ina sochii tajaajilaa","Cases by location and time":"Dhimmoota bakkaafi yeroo irratti","Based on recorded event locations and intake times.":"Bakkaafi yeroo galmee taatee irratti kan hundaa'e."}};
const monthly=[{name:"Jan",events:38,response:31},{name:"Feb",events:54,response:26},{name:"Mar",events:47,response:29},{name:"Apr",events:71,response:22},{name:"May",events:62,response:25},{name:"Jun",events:82,response:19}], status=[{name:"New",value:18},{name:"Assigned",value:25},{name:"Ongoing",value:31},{name:"Solved",value:26}], colors=["#315ff4","#8055d6","#e28323","#159879"];

function icon(label:string){return label.includes("Dashboard")?<LayoutDashboard/>:label.includes("Notification")?<Bell/>:label.includes("Report")||label==="Analytics"?<FileBarChart/>:label.includes("Department")?<Building2/>:label.includes("User")||label.includes("Operator")?<Users/>:label.includes("Settings")||label.includes("Profile")?<Settings/>:<ClipboardList/>}
function Charts({performance=false,events,t}:{performance?:boolean;events:EventRow[];t:(key:string)=>string}){const slots=["08–10","10–12","12–14","14–16"],locations=[...new Set(events.map(e=>e.location))].slice(0,5),heat=locations.map(location=>[location,...slots.map((_,index)=>events.filter(e=>{const hour=Number(e.time.split(":")[0]);return e.location===location&&Number.isFinite(hour)&&hour>=8+index*2&&hour<10+index*2}).length)]);return <section className="analytics"><article><h3>{performance?t("Cases handled by month"):t("Events by month")}</h3><ResponsiveContainer width="100%" height={220}><BarChart data={monthly}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="events" fill="#315ff4" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></article><article><h3>{t("Response-time trend")}</h3><ResponsiveContainer width="100%" height={220}><LineChart data={monthly}><CartesianGrid/><XAxis dataKey="name"/><YAxis/><Tooltip/><Line type="monotone" dataKey="response" stroke="#e28323" strokeWidth={3}/></LineChart></ResponsiveContainer></article><article><h3>{t("Case status")}</h3><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={status} dataKey="value" outerRadius={72}>{status.map((entry,i)=><Cell key={entry.name} fill={colors[i]}/>)}</Pie><Legend/><Tooltip/></PieChart></ResponsiveContainer></article><article className="heat-card"><h3>{t("Service activity heat map")}</h3><p>{t("Cases by location and time")}</p><div className="heatmap"><span></span>{slots.map(x=><b key={x}>{x}</b>)}{heat.map(([location,...values])=><Fragment key={String(location)}><strong>{location}</strong>{values.map((v,i)=><i key={`${location}-${slots[i]}`} style={{opacity:Number(v)?Math.min(.35+Number(v)/4,1):.16}} title={`${v} ${t("events")}`}>{v}</i>)}</Fragment>)}</div><small>{t("Based on recorded event locations and intake times.")}</small></article></section>}

export default function Portal({role,name,page}:{role:Role;name:string;page:string}) {
 const router=useRouter();
 const searchParams=useSearchParams();
 const [events,setEvents]=useState(seed),[q,setQ]=useState(""),[statusFilter,setStatus]=useState(""),[priority,setPriority]=useState(""),[modal,setModal]=useState(false),[notice,setNotice]=useState(""),[notices,setNotices]=useState<Notice[]>([]),[theme,setTheme]=useState<"light"|"dark">("light"),[lang,setLang]=useState<keyof typeof copy>("en");
 const item=nav[role].find(([id])=>id===page)||nav[role][0], active=item[1], t=(key:string)=>(phrases[lang] as Record<string,string>)[key]||(copy[lang] as Record<string,string>)[key]||(phrases.en as Record<string,string>)[key]||(copy.en as Record<string,string>)[key]||key;
 const editable=role==="OPERATOR"||(role==="DEPARTMENT_OFFICER"&&page!=="dashboard"&&page!=="register-event"), performance=/performance|response-time/.test(page), focused=page!=="dashboard", eventFromNotification=searchParams.get("event");
 const view=useMemo(()=>events.filter(e=>Object.values(e).join(" ").toLowerCase().includes(q.toLowerCase())&&(!statusFilter||e.status===statusFilter)&&(!priority||e.priority===priority)),[events,q,statusFilter,priority]);
 useLayoutEffect(()=>{setTheme((localStorage.getItem("cc9141-theme") as "light"|"dark")||"light");setLang((localStorage.getItem("cc9141-language") as keyof typeof copy)||"en")},[]);
 useEffect(()=>{document.documentElement.lang=lang==="am"?"am":lang==="om"?"om":"en";localStorage.setItem("cc9141-language",lang)},[lang]);
 useLayoutEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("cc9141-theme",theme)},[theme]);
 useEffect(()=>{let live=true;const load=async()=>{try{const r=await fetch("/api/notifications");if(r.ok&&live)setNotices(await r.json())}catch{}};load();const id=setInterval(load,30000);return()=>{live=false;clearInterval(id)}},[]);
 useEffect(()=>{let live=true;fetch("/api/events?limit=100").then(r=>r.ok?r.json():null).then(data=>{if(!live||!data?.items?.length)return;setEvents(data.items.map((e:any)=>({_id:e._id,id:e.eventId,caller:e.callerName,category:e.category,department:e.department?.name||"Unassigned",location:e.location,priority:e.priority,status:e.status,time:new Date(e.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}),operator:e.operator?._id||e.operator,assignedOfficer:e.assignedOfficer?._id||e.assignedOfficer}))) }).catch(()=>{});return()=>{live=false}},[]);
 function go(id:string){router.push(`/${role==="DEPARTMENT_OFFICER"?"department":role.toLowerCase()}/${id}`)}
 async function openNotification(n:Notice){try{if(!n.read)await fetch("/api/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({ids:[n._id]})});setNotices(items=>items.map(item=>item._id===n._id?{...item,read:true}:item));if(n.event)router.push(`/${role==="DEPARTMENT_OFFICER"?"department":role.toLowerCase()}/${role==="DEPARTMENT_OFFICER"?"assigned-events":"manage-events"}?event=${n.event}`)}catch{setNotice("Unable to open this notification. Please try again.")}}
 async function logout(){try{const r=await fetch("/api/auth/logout",{method:"POST"});if(!r.ok)throw Error();location.assign("/")}catch{setNotice("Unable to sign out. Please try again.")}}
 async function update(e:EventRow){const defaultStatus=e.status==="New"?"Assigned":e.status==="Assigned"?"Ongoing":"Solved";const requested=role==="DEPARTMENT_OFFICER"?window.prompt("Set status: Assigned, Ongoing, Solved, or Unsolved",defaultStatus):defaultStatus;const next=["Assigned","Ongoing","Solved","Unsolved"].includes(requested||"")?requested!:defaultStatus;const remarks=role==="DEPARTMENT_OFFICER"?(window.prompt("Write the update for the operator:","Department update sent to operator.")||"Department update sent to operator."):"Operator update sent to department.";setEvents(rows=>rows.map(x=>x.id===e.id?{...x,status:next}:x));try{if(e._id){const r=await fetch(`/api/events/${e._id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:next,remarks})});if(!r.ok)throw Error();}setNotice(role==="DEPARTMENT_OFFICER"?"Progress saved and operator notified.":"Event status updated.");}catch{setNotice("Unable to save this update. Please try again.")}}
 async function followUp(e:EventRow){if(!e._id){setNotice("Save this event before recording a follow-up.");return;}const note=window.prompt("Record the citizen follow-up:");if(!note)return;try{const r=await fetch(`/api/events/${e._id}/followups`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({note})});if(!r.ok)throw Error();setNotice("Citizen follow-up recorded.");}catch{setNotice("Unable to record the follow-up. Please try again.")}}
 async function create(f:FormData){const payload={callerName:f.get("caller"),phoneNumber:f.get("phone"),category:f.get("category"),description:f.get("description"),department:f.get("department"),location:f.get("location"),priority:f.get("priority")};try{const r=await fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw Error();const e=await r.json();setEvents(rows=>[{_id:e._id,id:e.eventId,caller:e.callerName,category:e.category,department:String(f.get("department")),location:e.location,priority:e.priority,status:e.status,time:"Now"},...rows]);setModal(false);setNotice("Event registered and routed successfully.");}catch{setNotice("Unable to register event. Please check the required fields.")}}
 const displayEvents=eventFromNotification?view.filter(x=>x._id===eventFromNotification):page==="critical-events"?view.filter(x=>x.priority==="Critical"):page==="assigned-events"?view.filter(x=>x.status!=="Solved"):view;
 return <div className={"portal "+theme}><aside><div className="portal-logo"><Activity/><b>9141</b><span>CALL CENTER</span></div><div className="portal-user"><b>{name}</b><small>{titles[role]}</small></div>{nav[role].map(([id,label])=><button key={id} className={id===page?"chosen":""} onClick={()=>go(id)}>{icon(label)}{t(label as keyof typeof copy.en)}</button>)}<button onClick={logout}><LogOut/>{t("Logout")}</button></aside><main><header><div><p>{titles[role].toUpperCase()} PORTAL</p><h1>{t(active as keyof typeof copy.en)}</h1></div><div className="portal-tools"><select aria-label="Language" value={lang} onChange={e=>{const value=e.target.value as keyof typeof copy;setLang(value);localStorage.setItem("cc9141-language",value)}}><option value="en">English</option><option value="am">አማርኛ</option><option value="om">Afaan Oromo</option></select><button className="icon" aria-label="Toggle colour theme" onClick={()=>{const value=theme==="light"?"dark":"light";setTheme(value);localStorage.setItem("cc9141-theme",value)}}>{theme==="light"?<Moon/>:<Sun/>}</button><button className="icon notify" aria-label="Notifications" onClick={()=>go("notifications")}><Bell/>{notices.some(n=>!n.read)&&<i/>}</button></div></header><section className="portal-intro"><div><h2>{page==="dashboard"?`Welcome back, ${name}`:active}</h2><p>{page==="dashboard"?"A focused overview of service delivery, priority cases and updates.":"Use this workspace to complete the selected task without leaving your role portal."}</p></div>{editable&&(page==="register-event"||page==="dashboard")&&<button className="primary" onClick={()=>setModal(true)}><Plus/>Register event</button>}</section>
 {page==="dashboard"&&<><div className="portal-cards">{[["Total events","1,284"],["Open events",String(events.filter(e=>e.status!=="Solved").length)],["Critical events","12"],["Avg. response","24m"]].map(x=><article key={x[0]}><Activity/><p>{x[0]}</p><h2>{x[1]}</h2><small>Updated today</small></article>)}</div><Charts events={events} t={t}/></>}
 {performance&&<><div className="portal-cards"><article><Activity/><p>Resolution rate</p><h2>86%</h2><small>+4.2% this month</small></article><article><Activity/><p>Median response</p><h2>22m</h2><small>2m faster than target</small></article><article><Activity/><p>{t("events")} completed</p><h2>346</h2><small>Across all departments</small></article><article><Activity/><p>Escalations</p><h2>18</h2><small>Needs supervisor review</small></article></div><Charts performance events={events} t={t}/></>}
 {page==="notifications"&&<section className="notice-list"><div className="section-heading"><div><h3>Live updates</h3><p>New department responses and assignments refresh automatically.</p></div><button className="link" onClick={async()=>{await fetch("/api/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({ids:notices.filter(n=>!n.read).map(n=>n._id)})});setNotices(n=>n.map(x=>({...x,read:true})))}}>Mark all read</button></div>{notices.length?notices.map(n=><article key={n._id} className={n.read?"":"unread"} onClick={()=>openNotification(n)} role={n.event?"button":undefined} tabIndex={n.event?0:undefined} onKeyDown={e=>{if(n.event&&(e.key==="Enter"||e.key===" "))openNotification(n)}}><MessageSquare/><div><b>{n.title}</b><p>{n.message}</p><small>{new Date(n.createdAt).toLocaleString()}</small></div></article>):<div className="empty"><Bell/><h3>No updates yet</h3><p>Assignments and department responses will appear here.</p></div>}</section>}
 {(page==="settings"||page==="profile")&&<section className="settings-grid"><article><Settings/><h3>Display preferences</h3><p>Choose how the portal feels on this device.</p><div className="setting-row"><span>{t("Theme")}</span><button className="link" onClick={()=>{const value=theme==="light"?"dark":"light";setTheme(value);localStorage.setItem("cc9141-theme",value)}}>{theme==="light"?t("Light"):t("Dark")}</button></div><div className="setting-row"><span>{t("Language")}</span><select value={lang} onChange={e=>setLang(e.target.value as keyof typeof copy)}><option value="en">English</option><option value="am">አማርኛ</option><option value="om">Afaan Oromo</option></select></div></article><article><Users/><h3>{name}</h3><p>{titles[role]} account</p><div className="setting-row"><span>Account security</span><CheckCircle2/></div><div className="setting-row"><span>Session</span><button className="link" onClick={logout}>Sign out</button></div></article></section>}
 {page==="reports"&&<><section className="report-actions"><h3>Generate reports</h3><p>Daily, weekly, monthly and yearly event reports are available in printable and Excel-ready formats.</p><div><a href="/api/reports?period=daily&format=csv">Export Excel / CSV</a><button onClick={()=>print()}>Print report</button></div></section><Charts events={events} t={t}/></>}
 {!["dashboard","notifications","settings","profile","reports","operator-performance","department-performance","response-time","analytics"].includes(page)&&<section className="portal-table"><div className="table-title"><div><h3>{page==="assigned-events"?"My assigned tasks":page==="follow-up"?"Follow-up workspace":"Events workspace"}</h3><p>{role==="DEPARTMENT_OFFICER"?"Accept cases, post progress, and notify the operator.":"Search, filter, and manage citizen service cases."}</p></div><label><Search/><input placeholder="Search events" value={q} onChange={e=>setQ(e.target.value)}/></label></div><div className="filters"><select value={statusFilter} onChange={e=>setStatus(e.target.value)}><option value="">All status</option>{["New","Assigned","Ongoing","Solved","Unsolved"].map(x=><option key={x}>{x}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priority</option>{["Low","Medium","High","Critical"].map(x=><option key={x}>{x}</option>)}</select><span>{displayEvents.length} results</span></div><div className="table-scroll"><table><thead><tr><th>Event</th><th>Caller / category</th><th>Department</th><th>Location</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{displayEvents.map(e=><tr key={e.id}><td><b>{e.id}</b><small>{e.time}</small></td><td><strong>{e.caller}</strong><small>{e.category}</small></td><td>{e.department}</td><td><MapPin size={13}/>{e.location}</td><td><span className={"pill "+e.priority.toLowerCase()}>{e.priority}</span></td><td><span className={"state "+e.status.toLowerCase()}>{e.status}</span></td><td>{editable?<button className="link" onClick={()=>update(e)}>{role==="DEPARTMENT_OFFICER"?"Send update":"Update"}</button>:"View"}</td></tr>)}</tbody></table></div></section>}
 {modal&&<div className="modal-bg"><form className="portal-modal" action={create}><button type="button" className="close" onClick={()=>setModal(false)}><X/></button><p>NEW INTAKE</p><h2>Register citizen event</h2><div className="portal-form"><label>Caller name<input required name="caller"/></label><label>Phone number<input required name="phone" inputMode="tel"/></label><label>Category<input required name="category"/></label><label>Location<input required name="location"/></label><label className="wide">Description<textarea required name="description" rows={3}/></label><label>Department<select name="department">{["Police","Fire","Health","Water","Electricity","Road Authority","Sanitation","Traffic Police"].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select name="priority">{["Low","Medium","High","Critical"].map(x=><option key={x}>{x}</option>)}</select></label></div><button className="primary">Register & escalate</button></form></div>}{notice&&<div className="toast">✓ {notice}</div>}</main></div>
}
