import mongoose from "mongoose";
import crypto from "node:crypto";
import fs from "node:fs";
function loadEnv(){try{for(const line of fs.readFileSync(".env.local","utf8").split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].trim().replace(/^['"]|['"]$/g,"");}}catch{}}
loadEnv();
const uri=process.env.MONGODB_URI?.trim();
if(!uri||uri.includes("<username>")||uri.includes("<password>")){console.error("MONGODB_URI is not configured. Replace the Atlas placeholder in .env.local, then run npm run seed.");process.exit(1)}
const hashPassword=p=>{const salt=crypto.randomBytes(16).toString("hex");return `scrypt:${salt}:${crypto.scryptSync(p,salt,64).toString("hex")}`};
try{const db=await mongoose.connect(uri,{serverSelectionTimeoutMS:10000});const users=db.connection.collection("users"),departments=db.connection.collection("departments");const departmentData=["Police","Fire","Health","Water","Electricity","Road Authority","Sanitation","Traffic Police"].map(name=>({name,code:name.replace(/[^A-Za-z]/g,"").slice(0,4).toUpperCase(),active:true,createdAt:new Date(),updatedAt:new Date()}));for(const d of departmentData)await departments.updateOne({name:d.name},{$setOnInsert:d},{upsert:true});const police=await departments.findOne({name:"Police"});const roles=[['Administrator','admin@callcenter9141.local','ADMIN'],['Operator','operator@callcenter9141.local','OPERATOR'],['Supervisor','supervisor@callcenter9141.local','SUPERVISOR'],['Department Officer','officer@callcenter9141.local','DEPARTMENT_OFFICER',police?._id]];for(const [name,email,role,department] of roles)await users.updateOne({email},{$set:{name,email,role,active:true,...(department?{department}:{})},$setOnInsert:{passwordHash:hashPassword('ChangeMe9141!'),createdAt:new Date(),updatedAt:new Date()}},{upsert:true});console.log('Seed complete. Default password: ChangeMe9141!');await mongoose.disconnect();}catch(e){console.error(`Seed failed: ${e.message}`);process.exit(1)}
